### ISSUE TITLE
'ADD' back sidedef button missing on Linux build linedef ?

### ISSUE THREAD

**Issue by smeghammer** [ioan-chera/eureka-editor#123]
Following a PM conversation with another DW member, we discovered that the "[ADD] back linedef" feature present on the Windows build of v1.27b is not present on v1.27b Linux build (Linux Mint, and Ubuntu 20.04). 

**Windows:**
![image](https://user-images.githubusercontent.com/73583806/153768383-92cd0408-f667-478b-81eb-7dfe87bb55e5.png)

**Linux Mint/Ubuntu 20.04:**
![image](https://user-images.githubusercontent.com/73583806/153768421-4e89a5f3-0d3a-413a-9c25-f375e92e9ccc.png)

Is this feature planned to be added to Linux builds?

**Comment by andwj** [comment]
Go into Preferences, the Editing tab, and click on "enable the ADD / DEL buttons".

**Comment by ioan-chera** [comment]
> Go into Preferences, the Editing tab, and click on "enable the ADD / DEL buttons".

Oh, your username is strongly familiar! Are you him? Greetings if so!

**Comment by andwj** [comment]
Yeah it's me, greetings to you to, hope you are well!

I was going to close this issue, but wasn't sure whether to wait for the original poster to reply.

**Comment by smeghammer** [comment]
Yes, thank you - please close.

**Comment by andwj** [comment]
hmmm, I thought there was a Close button here, but cannot find it now, so I guess I don't have the required permissions to close issues.

**Comment by smeghammer** [comment]
Oh looks like I can - probably because I opened it...
Closing.
