### ISSUE TITLE
compiler error when building at HEAD

### ISSUE THREAD

**Issue by stevesan** [ioan-chera/eureka-editor#130]
`/Users/***/eureka-editor/src/objid.h:81:2: error: definition of implicit copy assignment operator for 'Objid' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
        Objid(const Objid &other) = default;
        ^
/Users/***/eureka-editor/src/e_checks.cc:1463:8: note: in implicit copy assignment operator for 'Objid' first required here
                        obj = hover::getNearestSector(inst.level, pos2);
                            ^
1 error generated.`

i can fix this by commenting out the copy constructor or adding an explicit operator= implementation. thoughts? how can i check which version of clang it's using? the default one i have is:
`gcc --version
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
`

**Comment by ioan-chera** [comment]
I've added a `default` copy assignment operator. Let's hope this is enough to make it build! Thanks.
