### ISSUE TITLE
Consistent segmentation faults when splitting linedef in half on new project

### ISSUE THREAD

**Issue by boomlinde** [ioan-chera/eureka-editor#152]
# Steps to reproduce

1. Build from source (commit 21ace56882d457f34911342c45c2fba5c2734862, cc is GCC 12.2.0)
2. Run and create a new project. I select doom2/vanilla/Doom Format, add no resource wads and call it "test.wad"
3. Switch to Linedefs mode with `l`
4. Select the top line of the default room
5. Press `k` to split the linedef

At this point, I get the segfault. If I open a map from doom2.wad and split linedefs in map01, the same problem does not occur.

# Analysis

I rebuilt with debug symbols (`cmake . -DCMAKE_BUILD_TYPE=debug && make`) and could reproduce it then, as well. This is the output from GDB:

    Thread 1 "eureka" received signal SIGSEGV, Segmentation fault.
    LinedefModule::splitLinedefAtVertex (this=0x5555557b96e8 <gInstance+520>, op=..., ld=1, new_v=4)
        at /home/boomlinde/src/eureka-editor/src/e_linedef.cc:930
    930             *L2 = *L;

`L` is null, which I presume causes the segfault :

    L = std::unique_ptr<LineDef> = {get() = 0x0}

Please let me know if you need any further info!

**Comment by ioan-chera** [comment]
Looks like the classic array `realloc` problem. Sad thing is that with raw pointers this wasn't a problem! I need to fix it so it doesn't happen again...

**Comment by ioan-chera** [comment]
Fixed the problem.
