### ISSUE TITLE
Moving multiple vertexes alters alignment

### ISSUE THREAD

**Issue by Catoptromancy** [ioan-chera/eureka-editor#161]
Top two pillars are highlighted and will be moved left 6 grid units.
Middle two pillars were moved 2 grid units left and alignment was altered a little.
Bottom two pillars were moved 6 units at once.
This does not happen in last release.

Pillars can actually move without alignment issue but need to move one grid unit at a time. 

https://www.geocities.ws/catodemos/doom/eureka/eur1-joined-vertical.png

**Comment by ioan-chera** [comment]
I'll check. Glad that GeoCities still exists.

**Comment by ioan-chera** [comment]
Hopefully fixed!
