### ISSUE TITLE
[Linux] Conform to XDG Base Directory standard

### ISSUE THREAD

**Issue by elf-alchemist** [ioan-chera/eureka-editor#163]
In an effort to cleanup Linux users `$HOME` directory, I'd like request Eureka add support to storing it's files in accordance to the XDG Base Directory spec, storing them in their respective paths, for a nicer, cleaner, tidier `$HOME`.

[Unofficial spec](https://xdgbasedirectoryspecification.com)

![image](https://github.com/ioan-chera/eureka-editor/assets/108543697/f34f4ae5-8e47-4d9d-8745-b059b3f8474d)

**Comment by ioan-chera** [comment]
done
