### ISSUE TITLE
Linked official web site does not exist

### ISSUE THREAD

**Issue by Raven-Singularity** [ioan-chera/eureka-editor#196]
The main page lists the project web site as: http://eureka-editor.sourceforge.net/

But this URL only returns:

```
503 Service Unavailable
No server is available to handle this request.
```

If the SourceForge.net web site is no longer being used, just remove the link?  Or is there an actual web page somewhere?

**Comment by ioan-chera** [comment]
For me it works… Perhaps hosting was the problem at that moment?

**Comment by Raven-Singularity** [comment]
That's weird!  It's working fine now, you're right.  I guess it was just down for a few minutes.

When I went to it earlier, it gave that error -- even after reloading it a few times.  And the error sounded like SourceForge was no longer hosting it.  Strange.
