### ISSUE TITLE
error when building from source

### ISSUE THREAD

**Issue by Acetsetebos** [ioan-chera/eureka-editor#24]
I cloned the git repo and after checking to make sure I had all the required packages I ran `make` and got this error:

g++ -O2 -g -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -std=c++17 -fno-strict-aliasing -fwrapv -I/usr/include/freetype2 -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe -g -fvisibility-inlines-hidden -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT  -o obj_linux/Document.o -c src/Document.cc
In file included from src/e_basis.h:31,
                 from src/Document.h:22,
                 from src/Document.cc:19:
src/m_strings.h: In member function 'bool SString::noCaseStartsWith(const char*, int) const':
src/m_strings.h:95:58: error: 'strlen' was not declared in this scope
   95 |   return !y_strnicmp(data.c_str() + pos, c ? c : "", c ? strlen(c) : 0);
      |                                                          ^~~~~~
src/m_strings.h:29:1: note: 'strlen' is defined in header '<cstring>'; did you forget to '#include <cstring>'?
   28 | #include <vector>
  +++ |+#include <cstring>
   29 | 
src/m_strings.h: In member function 'bool SString::startsWith(const char*) const':
src/m_strings.h:109:49: error: 'strlen' was not declared in this scope
  109 |   return !strncmp(data.c_str(), c ? c : "", c ? strlen(c) : 0);
      |                                                 ^~~~~~
src/m_strings.h:109:49: note: 'strlen' is defined in header '<cstring>'; did you forget to '#include <cstring>'?
src/m_strings.h:109:11: error: 'strncmp' was not declared in this scope
  109 |   return !strncmp(data.c_str(), c ? c : "", c ? strlen(c) : 0);
      |           ^~~~~~~
src/m_strings.h:109:11: note: 'strncmp' is defined in header '<cstring>'; did you forget to '#include <cstring>'?
make: *** [Makefile:137: obj_linux/Document.o] Error 1

Anyone know what's going on? I'm running void linux btw.

**Comment by runlow** [comment]
Having trouble compiling it on linux. Lots of errors. Can post the diffs if I get it to compile.

**Comment by ioan-chera** [comment]
I'm working on it now. Hopefully I set up continuous integration so I don't neglect it later.

**Comment by ioan-chera** [comment]
Hopefully fixed (tested on Xubuntu 20.10).

**Comment by runlow** [comment]
Able to compile it now at e07c688b6630, thank you.
