### ISSUE TITLE
Cancelling "Delete Map" deletes the map

### ISSUE THREAD

**Issue by runlow** [ioan-chera/eureka-editor#28]
**Expected:**
Going to _File->Delete Map_ and pressing _Cancel_ on the question should just bring me back to the map I was editing.

**Actual:**
_Pressing File->Delete Map->Cancel_ deletes the map anyway. (deleted map no longer accessible from "Open Map", next one is opened)

Accidentally lost a whole map I was working because of this. (not a big deal as I can make it anew but not super convenient)

Tested it on Archlinux, Eureka built from b5f1b5087acf330

![2021-02-28-071059_626x202_scrot](https://user-images.githubusercontent.com/2176657/109410669-5ef27200-7994-11eb-9226-fcf1624b39a1.png)

**Comment by ioan-chera** [comment]
This is awful and is really my fault. I've fixed it, but it really calls for the importance of testing.

**Comment by runlow** [comment]
No worries about the map, it wasn't too advanced. Remade it since.

Confirmed that this is now fixed in b188f2391. Thank you
