### ISSUE TITLE
Flats and textures no longer previewed

### ISSUE THREAD

**Issue by runlow** [ioan-chera/eureka-editor#30]
Built from b5f1b5087acf3, tested on Archlinux.

**Expected:**
Flats and textures shown in the editor sidebar as they would appear in the game/3d view/2d view (without lighting).

**Actual:**
![2021-02-28-075624_1920x1080_scrot](https://user-images.githubusercontent.com/2176657/109411528-b267be80-799a-11eb-93b0-a3fd116b3260.png)
![2021-02-28-075632_1920x1080_scrot](https://user-images.githubusercontent.com/2176657/109411530-b562af00-799a-11eb-9486-bafdc046bf96.png)

**Comment by ioan-chera** [comment]
Fixed

**Comment by runlow** [comment]
Seems fixed now on b188f2391a50
Thank you
