### ISSUE TITLE
Placing new vertex doesn't update the texture in 2d view

### ISSUE THREAD

**Issue by runlow** [ioan-chera/eureka-editor#32]
**Expected:**
Placing a new vertex should make the texture in 2d view adjust to the new shape of the sector.

**Actual:**
The texture seems to look as if nothing was changed.

**Steps:**
Create a new wad archive.
Press **v** for vertices.
Place a point inside the rectangle.

Tested on Archlinux, built from b5f1b5087acf33028cc70a5
![2021-02-28-082444_702x634_scrot](https://user-images.githubusercontent.com/2176657/109412266-e1802f00-799e-11eb-899a-7f6386390fd7.png)

**Comment by ioan-chera** [comment]
Fixed.

**Comment by runlow** [comment]
Confirming that it's fixed now in b188f2391a50
Thank you
