### ISSUE TITLE
Pressing "Save" on dialog doesn't do anything

### ISSUE THREAD

**Issue by runlow** [ioan-chera/eureka-editor#33]
May be related to #28 

**Expected:**
You make a modification. You press Ctrl+T. It asks you if you want to save changes before previewing the map in the game. You click "Save" .....and then the editor either just saves and that's it, or it saves and the game runs the saved wad/map with the modifications you just made.

**Actual:**
You make a modification. You press Ctrl+T. It asks you if you want to save changes before previewing the map in the game. You click "Save" ....nothing happens

You have to press Ctrl+S and press Ctrl+T and *then* it previews it as expected.

Tested on Archlinux b5f1b5087acf33028cc

![2021-02-28-083525_1104x499_scrot](https://user-images.githubusercontent.com/2176657/109413268-6752a900-79a4-11eb-80ed-88ee16c12896.png)

**Comment by ioan-chera** [comment]
Probably related to #18: the message box from your screenshot doesn't have a title, but it really should have "Eureka - Confirmation". It also doesn't seem to have a margin.

**Comment by ioan-chera** [comment]
Fixed with #28.

**Comment by runlow** [comment]
Seems fixed now. Thank you
