### ISSUE TITLE
Fix CMake to work on Linux and replace Makefile

### ISSUE THREAD

**Issue by ioan-chera** [ioan-chera/eureka-editor#38]
We need CMake if we want to easily integrate Google Test and make multiple small programs. Start with Linux.

**Comment by runlow** [comment]
Was able to build b188f2391a500d9d with `cmake` on Archlinux without any issue.

Used these commands:
```
git clone https://github.com/ioan-chera/eureka-editor.git
cd eureka-editor
mkdir build
cmake -B build
make -C build
```
