### ISSUE TITLE
texture offset crashes in 3d mode

### ISSUE THREAD

**Issue by runlow** [ioan-chera/eureka-editor#42]
Steps to reproduce the crash:

1. Load or create a new map
2. press `l` for linedef (or `e` `w`)
3. hover with the mouse over a wall (don't click)
4. hold down the `r` key and move the mouse, keep moving your mouse cursor outside the boundaries of the wall rectangle (no crash)
5. click once on the wall so that the lines turn from yellow to orange around the rectangle
6. press and hold `r` and move around the mouse cursor again - as soon as you move the mouse cursor outside of the rectangle - Eureka will crash

Tested with 61a308bb48a25a1 built on Archlinux

**Comment by ioan-chera** [comment]
Fixed.

**Comment by runlow** [comment]
Confirmed that this is fixed in 95fae493baa75. Thank you!

**Comment by runlow** [comment]
By the way you can [close issues by mentioning them in the commit](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
