### ISSUE TITLE
the make command rebuilds everything

### ISSUE THREAD

**Issue by runlow** [ioan-chera/eureka-editor#43]
**Expected:**
When I do `git pull` and then `make -C build` only the parts that changed get compiled (usually very quick with other projects I do this with)

**Actual:**
Everything seems to be rebuilt as a whole from scratch every time - even when the change is minor. It takes a good few minutes to compile everything.

Tested on Archlinux 95fae493baa75

I may be doing something wrong. Do I need to pass some argument to only build parts that changed?

**Comment by ioan-chera** [comment]
Hmm, it works for me. I'm modifying a comment in a file like `ui_window.cc` and `make -C build` acts as expected: it only updates that `cc` file. And if I change the header, it only recompiles the CC files which use it in some way (which may be a lot of files).

Beware that I made a change to CMakeLists.txt recently, and there are more to come. Rerun cmake.

**Comment by ioan-chera** [comment]
@runlow I've made a notable change in CMakeLists now. Besides rerunning `cmake`, please know that the `eureka` product is going to be in the (build) folder, not (build)/src folder. If you run the latter, you'll keep running an outdated build.

**Comment by runlow** [comment]
No worries.

Not sure what's different or if I was doing something wrong, but it seems to build correctly now - only the parts that have changed.

```
rm -fr build
mkdir build
cmake -B build
make -C build
# builds everything for a few minutes
./build/eureka
# starts fine
echo -ne "\n;">>src/main.cc
make -C build
# builds quickly
```

Thanks a lot. Closing issue.
