### ISSUE TITLE
ZDiHF: action 160 (3D floor) does not render if lo-tag = 0 + any hi-tag

### ISSUE THREAD

**Issue by mistersector** [ioan-chera/eureka-editor#57]
Example: 
arg1 (lo-tag): 0
arg2 (type): 1
arg3 (flag): 0
arg4 (opacity): 255
arg5 (hi-tag): 3

sector tag: 768 (3 (hi-tag)*256 + 0(lo-tag))

3D floor will not render. 

If lo-tag = 1 and sector tag= 769, 3D floor renders.

**Comment by ioan-chera** [comment]
Fixed with #86
