### ISSUE TITLE
ZDiHF: hover over teleport lines does not highlight respective tagged sectors/things/lines

### ISSUE THREAD

**Issue by mistersector** [ioan-chera/eureka-editor#58]
Eureka is hard coded to highlight the sector tag in Doom Format, but in ZDoom in Hexen format, the action structure was shuffled to use 5 parameters. The Teleport Destination tag can be any one of the 5 parameters. It can also be a ThingID or lineID, depending on the action that triggered it.  Eureka should know how to display the Destination for each particular action.

https://zdoom.org/wiki/Category:Teleport_specials

77:TeleportGroup (tid, source, **destination**, movesource, fog)
215:Teleport_Line (thisid, **destid**, flip)
71:Teleport_NoFog (tid, useangle, **tag**, keepheight)
154:Teleport_NoStop (tid, **sectortag**, nofog)
76:TeleportOther (tid, **destination_tid**, fog)
78:TeleportInSector (**tag**, source_tid, dest_tid, fog, group_tid)
39:Teleport_ZombieChanger (tid, **tag**)

**Comment by ioan-chera** [comment]
Fixed with #86
