### ISSUE TITLE
optimize tag list

### ISSUE THREAD

**Issue by mistersector** [ioan-chera/eureka-editor#61]
While mapping, sector tags may change and create gaps in the list. While the Doom Format will likely never use all ~65k tags due to the 16-bit tag field, the Hexen format only allows 256 due to the 8-bit tag field.  Large projects need to allocate sector tags wisely to avoid tag depletion.

A new tool to optimize tags could make a gapped sector tag list contiguous.

eg 1 2 4 becomes 1 2 3

This tool should also update the affected actions on lines and things.

**Comment by ioan-chera** [comment]
While I didn't add the exact thing you requested (compacting the tags to consecutive numbers), I did improve the "get free tag" operation to also find tags within the gaps, so if you have tags 0, 1, 2 and 4, now it will return 3, not 5 like previously. See if this solves your problem.

**Comment by mistersector** [comment]
That's a good solution. Thanks.

**Comment by ioan-chera** [comment]
Closed since the solution was accepted and uncertain if there's a real demand for compacting the tag list
