### ISSUE TITLE
Crash I found when creating new map

### ISSUE THREAD

**Issue by em-777** [ioan-chera/eureka-editor#69]
I keep encountering a crash when I create a new map in a wad. It will generate the map just fine, but when I make an edit to it such as removing a player start, then it will crash. Strangely enough, when I restart the program and open the map back up, I can edit it just fine. Here's what the console spat out:

Backed up wad to: /home/.../.eureka/backups/eurekatest/15.wad
Saving Map : MAP03 in /home/.../DOOM/dev/WIP/eurekatest.wad
BSP: Building nodes on MAP03
Writing '__EUREKA' lump
Writing recent list to: /home/.../.eureka/misc.cfg
Save user state to: /home/.../.eureka/cache/006E7B0DB0DD152C.dat
Backed up wad to: /home/.../.eureka/backups/eurekatest/16.wad
Created NEW map : MAP04
BSP: Building nodes on MAP04
Writing '__EUREKA' lump
Writing recent list to: /home/.../.eureka/misc.cfg
Save user state to: /home/.../.eureka/cache/0091006B7BBA1A41.dat
/usr/include/c++/11.1.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = Thing*; _Alloc = std::allocator<Thing*>; std::vector<_Tp, _Alloc>::reference = Thing*&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)

**Comment by ioan-chera** [comment]
Thanks for the report, but I think I need more info on this. Here are my questions:

1. What version (or build) of Eureka are you running? Built from source, or an official version (e.g. 1.27b)? If from source, can you tell me from which git commit, please?
2. What kind of game and port are you targeting? Vanilla, Boom, ZDoom, Doom, Hexen etc.?
3. Can it be reproduced by creating a new project on MAP01, editing it a little, then starting a Fresh Map on MAP02, and deleting the player 1 start? I tried it with the latest master build, but failed to reproduce it.

**Comment by em-777** [comment]
The version I'm using is v1.27b. I installed it from the Arch User Repository. I was making a wad for Vanilla Doom. I did as you requested and created a new project. I was able to edit MAP01 just fine. I then created a MAP02, and as soon as I tried to remove three of the player starts, the editor crashed.

**Comment by ioan-chera** [comment]
Probably fixed today.
