### ISSUE TITLE
Display any keyboard shortcuts in the menu

### ISSUE THREAD

**Issue by ioan-chera** [ioan-chera/eureka-editor#84]
Currently many commands also invoked in the menu have their keyboard shortcuts set in the user preferences, but don't appear set up in the menu. It would be good to always show the keyboard shortcut in the menu if there's something set.

- [x] Wait for #89 
- [x] Check why there's difference between startup and after accepting user preferences (it's because of multiple bindings coming up in different orders which shouldn't matter)
- [x] Find a way to pick the most suitable shortcut that doesn't display unicode garbage on the menu
- [x] Check how it looks like in Mac (fails, see new subtasks)
- [x] Fix how changing `shortcut` in macOS actually doesn't work for the system menu bar (unless FLTK release a stable build which fixes the issue; 1.4.x does it but is unstable for now). Work around it. EDIT: it actually was a programmer mistake.
- [x] Once macOS works, make sure that all advertised shortcuts work.
- [x] Wait for #87 (CANCELLED, it's not robust enough)

**Comment by ioan-chera** [comment]
Done.

**Comment by mistersector** [comment]
Thank you!
